Added OnClick and OnMouse actions for Canvas
BlazorExtensions/Canvas pull request #84
Opened 2020-06-16 14:31 UTC by KristofferStrube

As described in issue #83

2020-06-22 21:01 UTC, KristofferStrube commented
I accidentally continued working with other things on the same branch. That has been reverted now. I'm new to making Pull Requests.

2020-09-22 13:46 UTC, ummerland requested changes
Hi, perfect addition to the Canvas!
There are some other Events that can also be added however: OnPointerDown, OnPointerUp, OnPointerMove

2021-02-07 19:03 UTC, Thaina commented
Did `ondblclick` was included?

2021-02-07 20:12 UTC, KristofferStrube commented
Hey @ummerland I must have missed a notification at some point, sorry. But I added the handlers you described now. And added the handler that @Thaina requested as well together with the `OnContextMenu` handler.

2021-02-07 20:16 UTC, ummerland commented
Very nice, thanks @KristofferStrube

2021-02-07 20:18 UTC, ummerland approved these changes
Very good and practical addition, clean code

2021-02-08 01:55 UTC, Thaina commented
@ummerland Do we have any chance this would be updated in nuget? Or we need to build this ourselves? It seem this repo don't get any updated for a whole year

2021-02-15 05:30 UTC, attilah commented
Sorry for the late update, we coming to this package and get review the feature PR and also update the package to .NET 5.0, thanks for the contrib.

2021-02-25 10:21 UTC, KristofferStrube commented
@attilah regarding the conflict with `blazor.extensions.canvas.js` which is auto-generated. Which version should be used? Doesn't seem like it would actually need to change with the modifications I've made to the project.

2021-10-26 22:34 UTC, tbm0115 approved these changes

2021-10-27 15:16 UTC, KristofferStrube commented
@tbm0115 I had some problems with my merge as you can see, but there are no conflicts now. You can just squash my commits.

2022-02-20 20:42 UTC, neilgd commented
Hi,

I'm wondering if this change made it into the release, or maybe it got lost somewhere?

I get an error _System.InvalidOperationException: Object of type 'Blazor.Extensions.Canvas.BECanvas' does not have a property matching the name 'onmousedown'_

2022-02-21 00:19 UTC, KristofferStrube commented
Hey @neilgd,
No this never got merged into the master branch.

2023-04-07 17:57 UTC, sethfduke commented
> Hey @neilgd, No this never got merged into the master branch.

Any chance this is going to be merged at some point? Been sitting here for quite a while.

2025-11-03 22:06 UTC, closed without merging